### ISSUE TITLE
Create objects.custom_object

### ISSUE THREAD

**Issue by MarkDavidson** [CybOXProject/python-cybox#217]
Would it be possible to create a custom object? It's defined in the spec but I don't see it in the library.

Thank you.
-Mark

**Comment by gtback** [comment]
@MarkDavidson : Are you talking about the [CustomObject](https://stixproject.github.io/data-model/1.1.1/CustomObj/CustomObjectType/), which relies entirely on Custom Properties, or externally-defined objects that use `ObjectProperties` as an extension point?

In the former case, it might not be too difficult to add generic handling, as we already support [CustomProperties](https://github.com/CybOXProject/python-cybox/blob/master/cybox/common/object_properties.py#L66-L71). We would just need to add a new wrapper object with no specific properties of its own.

There have been other projects that have added other externally-defined objects (that have their own XSDs), but since they aren't defined in the CybOX standard, we haven't included the code in python-cybox.

I can help out either way.

**Comment by MarkDavidson** [comment]
@gtback,

I'm talking about the CustomObject, as you mention in the first line of your response. I wasn't talking about externally-defined objects (w/ XSDs), but that might be a good idea, too.

I'll be honest - I forget why I opened this issue in the first place. Since I no longer have an immediate reason for wanting this, I'll suggest that this item gets prioritized accordingly (e.g., if nobody else is asking for it, it can fall down the list a bit)

Thank you.
-Mark
