### ISSUE TITLE
Object relationships

### ISSUE THREAD

**Issue by geekscrapy** [CybOXProject/python-cybox#261]
How would you go about creating a Downloaded_From relationship using the current version?

		domain = helper.create_domain_name_observable('www.example.com')
		file = helper.create_file_hash_observable('foo.bar', '94f93e00fd12246...')

		download_frm = vocabs.ObjectRelationship(value='Downloaded_From')
		file.ObjectProperties.add_related(domain, download_frm)

Error is:

		>>> file_.ObjectProperties.add_related(domain, download_frm)
		Traceback (most recent call last):
		  File "<stdin>", line 1, in <module>
		AttributeError: 'Observable' object has no attribute 'ObjectProperties'

**Comment by gtback** [comment]
Hi, @geekscrapy .

The `helper.create_*_observable` functions return an `Observable`, rather than an `ObjectProperties` subclass (such as `File` or `DomainName`). To get this to work, you need to create the relationship between the `ObjectProperties`. The following works for me.

```python
from cybox import helper
from cybox.common import vocabs

domain = helper.create_domain_name_observable('www.example.com')
file = helper.create_file_hash_observable('foo.bar', '94f93e00fd12246...')

download_frm = vocabs.ObjectRelationship(value='Downloaded_From')
file.object_.properties.add_related(domain.object_.properties, download_frm)

print file.to_xml()
```

On a side note, the `helper` module is pretty out of date, and not actively maintained. It exists from a time before some of the more user-friendly APIs were created. Also, domain names should be represented as a DomainName object, rather than a URI object (the DomainName object did not exist when the helper was written). This is how I would write the code you have above:

```
from cybox.common.vocabs import ObjectRelationship
from cybox.core import Observables
from cybox.objects.file_object import File
from cybox.objects.domain_name_object import DomainName

f = File()
f.file_name = "foo.bar"
f.add_hash('94f93e00fd12246...')

d = DomainName()
d.value = "www.example.com"
f.add_related(d, ObjectRelationship.TERM_DOWNLOADED_FROM, inline=False)

print Observables([f, d]).to_xml()
``` 

Note that this is slightly different from your example in that the domain is not "embedded" inside the file object. If you would prefer that, remove the `inline=False` and change the last line to `Observables([f])`

Let me know if that's helpful, and I can close this issue.

**Comment by geekscrapy** [comment]
Thanks for that @gtback, just what I needed (new to Python!)

Are there many examples for relationships at the moment that you could point me at? I've had a good look but I couldn't find this kind of detail on how to create them...

**Comment by gtback** [comment]
There's not any great documentation right now, but I created an issue (#262) to do so.

Thanks for suggesting this, @geekscrapy .
