### ISSUE TITLE
add XML validation functionality

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/python-cybox#33]
Create a validate() utility method that verifies the correctness of the output/input document. This will likely need to use the lxml.etree XMLSchema class.

**Comment by ajnelson-nist** [comment]
Hi!  I tried using xmllint to validate some CybOX generated output recently, and I couldn't quite get it working.  There seemed to be several issues with the XSDs trying to reference on another.  Do you have any working examples of using lxml or xmllint (either would be fine, since it's libxml2 under the hood) to validate, say, one of the sample CybOX files in this repository?  Could that be integrated into the Python bindings as an example script?

**Comment by bworrell** [comment]
@ajnelson-nist , take a look at [stix-validator](https://pypi.python.org/pypi/stix-validator/) tool we've developed. It can validate [CybOX documents as well](http://stix-validator.readthedocs.org/en/stable/getting_started.html#cybox-document-validator).

**Comment by ajnelson-nist** [comment]
Oh great, thanks!  Does that mean this Issue can be closed, then?

**Comment by bworrell** [comment]
Haha, I was just thinking about that :) I'm gonna close it now since stix-validator provides validation capabilities already. Thanks!
